# Generated by Django 4.0.4 on 2022-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_brewery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewery',
            name='address_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='address_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='county_province',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='created_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='updated_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='website_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
